name: flipperkit_dio_interceptor
description: flipperkit_dio_interceptor
version: 0.1.0
author: LiJianying <lijy91@foxmail.com>
homepage: https://github.com/leanflutter/flutter_flipperkit_plugins

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_flipperkit: ^0.0.27
  dio: ">=4.0.0 <6.0.0"
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter